### ISSUE TITLE
Traffic control not work

### ISSUE THREAD

**Issue by llyaiyyl** [shadowsocks/shadowsocks-hub#1]
hi，excuse me：
I follow the user guide to create a product with 100MB/monthly，then when a port tgraffic exceed 100MB，the Connection cannot be disconnected automatically
![image](https://user-images.githubusercontent.com/10733946/43876419-8d465ff2-9bc7-11e8-8ca0-313ce52191d9.png)
![image](https://user-images.githubusercontent.com/10733946/43876430-9caa5caa-9bc7-11e8-8979-7c093bde0a82.png)

**Comment by Eggham** [comment]
Well done! The good first issue. I have reproduced the problem. Will fix it soon...

**Comment by Eggham** [comment]
Fixed with 2d28481
